/**
 *    Copyright (C) 2021-present Carrot, Inc.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the Server Side Public License, version 1,
 *    as published by MongoDB, Inc.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    Server Side Public License for more details.
 *
 *    You should have received a copy of the Server Side Public License
 *    along with this program. If not, see
 *    <http://www.mongodb.com/licensing/server-side-public-license>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "lz4.h"
#include "lz4hc.h"
/* Header for class org_bigbase_compression_lz4_LZ4 */

#ifndef _Included_org_bigbase_compression_lz4_LZ4
#define _Included_org_bigbase_compression_lz4_LZ4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bigbase_compression_lz4_LZ4
 * Method:    compress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bigbase_compression_lz4_LZ4_compress
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_bigbase_compression_lz4_LZ4
 * Method:    decompress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bigbase_compression_lz4_LZ4_decompress
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_bigbase_compression_lz4_LZ4
 * Method:    compressDirect
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_compressDirect
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint);

JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_compressDirectHC
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint);

    JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_compressDirectAddress
    (JNIEnv *, jclass, jlong, jint, jlong, jint); 
    
    JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_compressDirectAddressHC
    (JNIEnv *, jclass, jlong, jint, jlong, jint, jint); 
/*
 * Class:     org_bigbase_compression_lz4_LZ4
 * Method:    decompressDirect
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_decompressDirect
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint);

JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_decompressDirectHC
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint);
    
    JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_decompressDirectAddress
    (JNIEnv *, jclass, jlong, jint, jlong, jint);
    
    JNIEXPORT jint JNICALL Java_org_bigbase_compression_lz4_LZ4_decompressDirectAddressHC
    (JNIEnv *, jclass, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
